import 'server-only'
import type { Descritor } from '@/lib/supabase/leitura'
import { LEITURA_TIPOS_ITEM, LEITURA_TIPOS_ITEM_ADMIN } from '@/lib/queries/formas/tipos-item'
import { LEITURA_PAPEL_ATUAL, LEITURA_PERFIL_OPERADOR } from '@/lib/queries/formas/auth'
import { LEITURA_FILA_PENDENCIAS_DASHBOARD } from '@/lib/queries/formas/dashboard'
import { LEITURA_DEVOLVER_AO_FORNECEDOR } from '@/lib/queries/formas/devolucao-fornecedor'
import {
  LEITURA_ITENS_PARA_PONTE,
  LEITURA_LANCAMENTOS_DA_REABERTURA,
  LEITURA_RESOLVER_PENDENCIAS_COM_LANCAMENTOS,
  LEITURA_TIPOS_ITEM_PARA_PONTE,
} from '@/lib/queries/formas/pendencias'
import {
  LEITURA_MOV_ITENS_DO_PERIODO,
  LEITURA_REL_ESTOQUE_ASOF,
  LEITURA_REL_FRESCOR_ITENS,
  LEITURA_REL_MOV_ITENS,
  LEITURA_REL_MOV_POR_MES,
  LEITURA_REL_POR_MOTIVO,
  LEITURA_REL_RESUMO,
  LEITURA_REL_SALDO_ITENS,
  LEITURA_TABELA_DO_PERIODO,
  LEITURA_ULTIMA_VERSAO_RELATORIO,
  LEITURA_ULTIMAS_MOVIMENTACOES,
} from '@/lib/queries/formas/relatorios'
import { LEITURA_APAGAR_CONFLITO, LEITURA_LADOS_DE_CONFLITO } from '@/lib/queries/formas/conflitos'
import {
  LEITURA_ATIVOS_DO_LOTE,
  LEITURA_CANDIDATAS_DUPLICATA,
  LEITURA_CRIAR_MOVIMENTACAO_COM_ITENS,
  LEITURA_ENVIO_MANUTENCAO,
  LEITURA_ITENS_DA_MOVIMENTACAO_A_ESTORNAR,
  LEITURA_LINHA_DO_TEMPO,
  LEITURA_LISTA_MOVIMENTACOES,
  LEITURA_LISTA_MOVIMENTACOES_POR_PATRIMONIO,
  LEITURA_MOV_PARA_DUPLICAR,
  LEITURA_SUGESTAO_COLABORADOR_MOV,
  LEITURA_SUGESTAO_SETOR_MOV,
  LEITURA_ULTIMA_MOV_DO_USUARIO,
} from '@/lib/queries/formas/movimentacoes'
import { LEITURA_MOTIVOS_ADMIN, LEITURA_SENHAS_ACESSO } from '@/lib/queries/formas/admin'
import {
  LEITURA_ANOTACOES_ATIVO,
  LEITURA_EXPORT_ATIVOS,
  LEITURA_FICHA_ATIVO,
  LEITURA_LISTA_ATIVOS,
  LEITURA_MESMA_IDENTIDADE,
  LEITURA_RECENTES_DO_OPERADOR,
  LEITURA_RESUMO_ATIVO,
  LEITURA_VINCULO_ATIVO,
} from '@/lib/queries/formas/ativos'
import {
  LEITURA_COLABORADORES_POR_NOME,
  LEITURA_FILA_CONSOLIDACAO,
  LEITURA_GRUPOS_A_CONSOLIDAR,
  LEITURA_RESUMO_CONSOLIDACAO,
  LEITURA_SUGESTAO_CADASTRO,
  LEITURA_SUGESTAO_LANCAMENTOS,
  LEITURA_SUGESTAO_MOVIMENTACOES,
} from '@/lib/queries/formas/colaboradores'
import { LEITURA_ULTIMA_COMPRA_DO_OPERADOR } from '@/lib/queries/formas/compras'
import { LEITURA_CHECAGENS_INTEGRIDADE } from '@/lib/queries/formas/dev'
import {
  LEITURA_APAGAR_ATIVO,
  LEITURA_APAGAR_ITEM,
  LEITURA_APAGAR_MOVIMENTACAO,
  LEITURA_BACKUP_ANOTACOES,
  LEITURA_BACKUP_ATIVOS,
  LEITURA_BACKUP_LANCAMENTOS_ITEM,
  LEITURA_BACKUP_MOVIMENTACOES,
  LEITURA_BACKUP_PENDENCIAS_ITEM,
  LEITURA_BACKUP_TERMOS_GERADOS,
  LEITURA_CANDIDATOS_DESTRUTIVO,
  LEITURA_FORCAR_ESTADO,
  LEITURA_FORCAR_SALDO,
  LEITURA_ITENS_DESTRUTIVO,
  LEITURA_MOVS_DESTRUTIVO,
  LEITURA_PREVIA_RESET,
  LEITURA_RESETAR_ACERVO,
  LEITURA_RESETAR_ITENS,
  LEITURA_TERMOS_DO_ATIVO_DESTRUTIVO,
} from '@/lib/queries/formas/dev-destrutivo'
import { LEITURA_EVENTOS_ADMIN } from '@/lib/queries/formas/eventos-admin'
import {
  LEITURA_BACKUP_ANOTACOES_IMPORT,
  LEITURA_BACKUP_ATIVOS_IMPORT,
  LEITURA_BACKUP_LANCAMENTOS_ITEM_IMPORT,
  LEITURA_BACKUP_MOVIMENTACOES_IMPORT,
  LEITURA_BACKUP_PENDENCIAS_ITEM_IMPORT,
  LEITURA_BACKUP_TERMOS_GERADOS_IMPORT,
  LEITURA_PAR_COM_PATRIMONIO_EM_OUTRA_FILIAL,
  LEITURA_PAR_SEM_PATRIMONIO_EM_OUTRA_FILIAL,
} from '@/lib/queries/formas/import-logs'
import {
  LEITURA_ACESSORIOS_DAS_MOVIMENTACOES,
  LEITURA_HISTORICO_LANCAMENTOS,
  LEITURA_HISTORICO_PARA_EXPORT,
  LEITURA_ITENS_ADMIN,
  LEITURA_ITENS_ATIVOS,
  LEITURA_ITENS_JUNTO_DO_ATIVO,
  LEITURA_LANCAMENTO_PARA_ESTORNO,
  LEITURA_LANCAMENTOS_SALDO_APOS,
  LEITURA_LANCAR_ITENS_LOTE,
  LEITURA_SALDO_COLABORADOR,
  LEITURA_ULTIMO_LANCAMENTO,
} from '@/lib/queries/formas/itens'
import { LEITURA_KITS_ADMIN, LEITURA_KITS_ATIVOS } from '@/lib/queries/formas/kits'
import { LEITURA_MOTIVOS_ATIVOS } from '@/lib/queries/formas/motivos'
import { LEITURA_FILA_PENDENCIAS, LEITURA_SERVICE_TAGS_PENDENCIAS } from '@/lib/queries/formas/pendencias-detalhe'
import { LEITURA_PENDENCIAS_ITEM_DO_ATIVO } from '@/lib/queries/formas/pendencias-item'
import {
  LEITURA_ALVOS_ASSINATURA_LOTE,
  LEITURA_ATIVOS_ID,
  LEITURA_CIDADES_DAS_FILIAIS,
  LEITURA_MOV_PARA_TERMO,
  LEITURA_TERMOS_DO_ATIVO,
  LEITURA_TERMOS_EXISTENTES_DO_CONJUNTO,
  LEITURA_URL_TERMO,
} from '@/lib/queries/formas/termos'
import { LEITURA_VOCAB_CATEGORIAS, LEITURA_VOCAB_ESTADOS } from '@/lib/queries/formas/vocabulario-import'

// O CATÁLOGO DE FORMAS — toda leitura migrada para a porta da leitura (F58 · Frentes C e E).
//
// É a lista que o conferidor de formas (`scripts/formas/conferir.mts`) percorre contra o banco:
// cada descritor aqui é uma forma que precisa ser PROVADA contra as linhas reais de produção antes
// do merge (decisão ii do Johnny). `catalogo.test.ts` exige que todo descritor exportado de
// `src/lib/queries/formas/**` esteja nesta lista — uma forma fora do catálogo seria uma forma que
// nunca passou pelo dado real.
export const CATALOGO: readonly Descritor[] = [
  // lote 1 — tipos de item
  LEITURA_TIPOS_ITEM,
  LEITURA_TIPOS_ITEM_ADMIN,
  // lote 1 — relatórios (a superfície do visualizador por senha)
  LEITURA_REL_ESTOQUE_ASOF,
  LEITURA_REL_SALDO_ITENS,
  LEITURA_REL_MOV_ITENS,
  LEITURA_REL_FRESCOR_ITENS,
  LEITURA_REL_MOV_POR_MES,
  LEITURA_REL_POR_MOTIVO,
  LEITURA_REL_RESUMO,
  LEITURA_ULTIMAS_MOVIMENTACOES,
  LEITURA_TABELA_DO_PERIODO,
  LEITURA_MOV_ITENS_DO_PERIODO,
  // lote 1 — o que a inferência de `paginarTodos` desmascarou fora de relatórios
  LEITURA_LADOS_DE_CONFLITO,
  LEITURA_LINHA_DO_TEMPO,
  // lote 2 — admin.ts
  LEITURA_MOTIVOS_ADMIN,
  LEITURA_SENHAS_ACESSO,
  // lote 2 — ativos.ts
  LEITURA_LISTA_ATIVOS,
  LEITURA_FICHA_ATIVO,
  LEITURA_VINCULO_ATIVO,
  LEITURA_ANOTACOES_ATIVO,
  LEITURA_RESUMO_ATIVO,
  LEITURA_RECENTES_DO_OPERADOR,
  LEITURA_EXPORT_ATIVOS,
  // lote 2 — colaboradores.ts
  LEITURA_FILA_CONSOLIDACAO,
  LEITURA_RESUMO_CONSOLIDACAO,
  LEITURA_COLABORADORES_POR_NOME,
  LEITURA_SUGESTAO_CADASTRO,
  LEITURA_SUGESTAO_MOVIMENTACOES,
  LEITURA_SUGESTAO_LANCAMENTOS,
  // lote 2 — compras.ts
  LEITURA_ULTIMA_COMPRA_DO_OPERADOR,
  // lote 2 — dev.ts (recibo — RPC só-dev, provada contra o corpo vivo)
  LEITURA_CHECAGENS_INTEGRIDADE,
  // lote 2 — dev-destrutivo.ts
  LEITURA_CANDIDATOS_DESTRUTIVO,
  LEITURA_MOVS_DESTRUTIVO,
  LEITURA_TERMOS_DO_ATIVO_DESTRUTIVO,
  LEITURA_ITENS_DESTRUTIVO,
  // recibo — RPC só-dev
  LEITURA_PREVIA_RESET,
  LEITURA_BACKUP_ATIVOS,
  LEITURA_BACKUP_MOVIMENTACOES,
  LEITURA_BACKUP_ANOTACOES,
  LEITURA_BACKUP_PENDENCIAS_ITEM,
  LEITURA_BACKUP_TERMOS_GERADOS,
  LEITURA_BACKUP_LANCAMENTOS_ITEM,
  // lote 2 — eventos-admin.ts
  LEITURA_EVENTOS_ADMIN,
  // lote 2 — import-logs.ts
  LEITURA_PAR_COM_PATRIMONIO_EM_OUTRA_FILIAL,
  LEITURA_PAR_SEM_PATRIMONIO_EM_OUTRA_FILIAL,
  LEITURA_BACKUP_ATIVOS_IMPORT,
  LEITURA_BACKUP_MOVIMENTACOES_IMPORT,
  LEITURA_BACKUP_ANOTACOES_IMPORT,
  LEITURA_BACKUP_TERMOS_GERADOS_IMPORT,
  LEITURA_BACKUP_PENDENCIAS_ITEM_IMPORT,
  LEITURA_BACKUP_LANCAMENTOS_ITEM_IMPORT,
  // lote 2 — itens.ts
  LEITURA_ITENS_ATIVOS,
  LEITURA_ITENS_ADMIN,
  LEITURA_HISTORICO_LANCAMENTOS,
  LEITURA_HISTORICO_PARA_EXPORT,
  LEITURA_LANCAMENTOS_SALDO_APOS,
  LEITURA_ULTIMO_LANCAMENTO,
  LEITURA_SALDO_COLABORADOR,
  LEITURA_ITENS_JUNTO_DO_ATIVO,
  LEITURA_ACESSORIOS_DAS_MOVIMENTACOES,
  // lote 2 — kits.ts
  LEITURA_KITS_ATIVOS,
  LEITURA_KITS_ADMIN,
  // lote 2 — motivos.ts
  LEITURA_MOTIVOS_ATIVOS,
  // lote 2 — movimentacoes.ts
  LEITURA_ENVIO_MANUTENCAO,
  LEITURA_ULTIMA_MOV_DO_USUARIO,
  LEITURA_MOV_PARA_DUPLICAR,
  LEITURA_SUGESTAO_COLABORADOR_MOV,
  LEITURA_SUGESTAO_SETOR_MOV,
  LEITURA_CANDIDATAS_DUPLICATA,
  LEITURA_LISTA_MOVIMENTACOES,
  LEITURA_LISTA_MOVIMENTACOES_POR_PATRIMONIO,
  // lote 2 — pendencias-detalhe.ts
  LEITURA_FILA_PENDENCIAS,
  LEITURA_SERVICE_TAGS_PENDENCIAS,
  // lote 2 — pendencias-item.ts
  LEITURA_PENDENCIAS_ITEM_DO_ATIVO,
  // lote 2 — termos.ts
  LEITURA_TERMOS_DO_ATIVO,
  // lote 2 — vocabulario-import.ts
  LEITURA_VOCAB_CATEGORIAS,
  LEITURA_VOCAB_ESTADOS,
  // lote 3 — auth.ts
  LEITURA_PAPEL_ATUAL,
  LEITURA_PERFIL_OPERADOR,
  // lote 3 — dashboard (app/(app)/page.tsx)
  LEITURA_FILA_PENDENCIAS_DASHBOARD,
  // lote 3 — colaboradores.ts
  LEITURA_GRUPOS_A_CONSOLIDAR,
  // lote 3 — conflitos.ts (recibo)
  LEITURA_APAGAR_CONFLITO,
  // lote 3 — dev-destrutivo.ts (recibos)
  LEITURA_APAGAR_ATIVO,
  LEITURA_APAGAR_MOVIMENTACAO,
  LEITURA_APAGAR_ITEM,
  LEITURA_RESETAR_ACERVO,
  LEITURA_RESETAR_ITENS,
  LEITURA_FORCAR_ESTADO,
  LEITURA_FORCAR_SALDO,
  // lote 3 — devolucao-fornecedor.ts (recibo)
  LEITURA_DEVOLVER_AO_FORNECEDOR,
  // lote 3 — itens.ts
  LEITURA_LANCAMENTO_PARA_ESTORNO,
  LEITURA_LANCAR_ITENS_LOTE,
  // lote 3 — movimentacoes.ts
  LEITURA_ATIVOS_DO_LOTE,
  LEITURA_ITENS_DA_MOVIMENTACAO_A_ESTORNAR,
  LEITURA_CRIAR_MOVIMENTACAO_COM_ITENS,
  // lote 3 — pendencias.ts
  LEITURA_TIPOS_ITEM_PARA_PONTE,
  LEITURA_ITENS_PARA_PONTE,
  LEITURA_LANCAMENTOS_DA_REABERTURA,
  LEITURA_RESOLVER_PENDENCIAS_COM_LANCAMENTOS,
  // lote 3 — relatorios.ts
  LEITURA_ULTIMA_VERSAO_RELATORIO,
  // lote 3 — termos.ts
  LEITURA_CIDADES_DAS_FILIAIS,
  LEITURA_MOV_PARA_TERMO,
  LEITURA_TERMOS_EXISTENTES_DO_CONJUNTO,
  LEITURA_URL_TERMO,
  LEITURA_ALVOS_ASSINATURA_LOTE,
  LEITURA_ATIVOS_ID,
  // lote 3 — ativos/identidade.ts
  LEITURA_MESMA_IDENTIDADE,
]
